url: 'https://bdub.digital'
baseurl: ''
# baseurl: '/'
permalink: pretty
title: 'Bdub.digital'
tagline: 'Leading Your Digital Transformation'
description:
  fr: "J’accompagne vos équipes dans leur transformation digitale en tant que CTO indépendant, en guidant la stratégie technologique et l'innovation pour convertir vos idées en succès mesurables."
  en: "I lead teams through digital transformation as a fractional CTO, guiding strategic technology initiatives and innovation to turn ideas into measurable success through strategic leadership and innovative solutions."

image: "images/og-image.png"

logo: "images/logo/logo.svg"

site-logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "48px"
  desktop_width: "180px"

home: 
  limit_services: 3

collections:
  services:
    output: true
    sort_by: weight
    permalink: /:collection/:title
  posts:
    output: true
    sort_by: date
    permalink: /:collection/:title

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-polyglot
  - jekyll-redirect-from
  - jekyll-timeago
  - jekyll-seo-tag

include: ['_pages']

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - images/screenshots/
  - firebase.json
  - functions/

languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["assets", "images/features", "images/illustrations", "sitemap.xml", "robots.txt"]
parallel_localization: false
lang_from_path: true
whitelist:
  - jekyll-redirect-from
sass:
    sourcemap: never