name: Deploy to Firebase Hosting on Push
'on':
  push:
    branches:
      - main

      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --config _config_staging.yml # --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch firebase.json from repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            firebase.json
          sparse-checkout-cone-mode: false
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: site
          path: _site
      - name: Deploy to Firebase live
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BDUBDIGITALTEST }}'
          channelId: live
          projectId: bdubdigitaltest
      - name: Deploy to Firebase live
        if: github.ref == 'refs/heads/dev'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BDUBDIGITALTEST }}'
          channelId: dev
          projectId: bdubdigitaltest